name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black~=24.4.2 pytest~=8.3.4
        pip install -e .
    - name: Check code style with Black
      run: |
        black -l 80 --check emmio tests
    - name: Test with pytest
      run: |
        pytest -v
