name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    # TODO: Uncomment this section when we want to test audio playback using
    # GitHub Actions. For now it seems too resource-intensive. We should
    # probably create another test configuration that will not run on every
    # commit.
    # name: Install system dependencies
    # run: |
    #   sudo apt-get update
    #   sudo apt-get install -y libmpv-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Check code style with Black
      run: |
        black --check emmio/ tests/
    - name: Check imports with isort
      run: |
        isort --check-only emmio/ tests/
    - name: Check types with Mypy
      run: |
        mypy emmio/ tests/
    - name: Test with pytest
      run: |
        pytest -v
